spring:
  application:
    name: eventapp
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: eventapp
            client-secret: qMuOyMewOXJ2ICSIcRZK6hLykHkDtpFA
            client-name: eventapp
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/proselyte

server:
  port: 8091

notificationapp:
  url: http://localhost:8092
